#!/usr/bin/env python3
"""
Closed-loop training: read weakest directions from eval, generate targeted scenarios,
run training, then re-evaluate to see improvement.
"""

import sys
import json
import importlib
import subprocess
from pathlib import Path

def load_training_data():
    """Load the training data generated by run_full_golden_eval."""
    try:
        with open("eval_for_training.json", "r") as f:
            data = json.load(f)
        return data
    except FileNotFoundError:
        print("Error: eval_for_training.json not found. Running evaluation first...")
        # Import and run evaluation
        try:
            from run_full_golden_eval import run_evaluation
            data = run_evaluation()
            if data is None:
                print("Evaluation failed. Cannot proceed.")
                sys.exit(1)
            return data
        except Exception as e:
            print(f"Failed to run evaluation: {e}")
            print("Please run 'python run_full_golden_eval.py' first.")
            sys.exit(1)

def generate_scenarios_for_weakness(weakness_info):
    """Generate training scenarios for a weak category using scenarioforge."""
    try:
        scenarioforge = importlib.import_module("scenarioforge")
        # Assume scenarioforge has a method to generate scenarios given a category and task details
        if hasattr(scenarioforge, "generate_scenarios"):
            scenarios = scenarioforge.generate_scenarios(
                category=weakness_info["category"],
                tasks=weakness_info["tasks"],
                target_score=0.8  # aim to get at least 80% in this category
            )
            return scenarios
        else:
            print("Warning: scenarioforge.generate_scenarios not found, using dummy scenarios.")
            # Dummy fallback: create scenarios based on category and tasks, with adaptive details
            scenarios = []
            current_score = weakness_info.get("current_score", 0)
            # Determine number of scenarios per task based on current score
            # Lower score means more practice needed
            base_scenarios = 3
            additional = max(0, int((0.8 - current_score) * 10))  # e.g., if score 0.5, add 3 scenarios
            num_per_task = base_scenarios + additional
            for task_name, _ in weakness_info["tasks"]:
                for i in range(num_per_task):
                    scenarios.append({
                        "type": "practice",
                        "category": weakness_info["category"],
                        "task_name": task_name,
                        "drill_type": "focused_review",
                        "difficulty": "hard" if current_score < 0.6 else "medium",
                        "session": i + 1
                    })
            return scenarios
    except ImportError:
        print("Error: Could not import scenarioforge.")
        sys.exit(1)

def run_training(scenarios):
    """Run training on scenarios using patchcourse."""
    try:
        patchcourse = importlib.import_module("patchcourse")
        if hasattr(patchcourse, "train_on_scenarios"):
            result = patchcourse.train_on_scenarios(scenarios)
            return result
        else:
            print("Warning: patchcourse.train_on_scenarios not found, skipping training.")
            return {"status": "skipped", "reason": "method not found"}
    except ImportError:
        print("Error: Could not import patchcourse.")
        sys.exit(1)

def main():
    print("=== Closed-Loop Training ===\n")
    
    # Step 1: Load evaluation data
    training_data = load_training_data()
    weakest_directions = training_data.get("weakest_directions", [])
    category_details = training_data.get("category_details", {})
    
    if not weakest_directions:
        print("No weak directions found. Evaluation may have failed.")
        sys.exit(1)
    
    print("Weakest directions from evaluation:")
    for category, score in weakest_directions:
        print(f"  {category}: {score:.3f}")
    
    # Step 2: For each weak direction, generate scenarios and train
    training_results = []
    for category, _ in weakest_directions:
        if category not in category_details:
            print(f"Warning: Category '{category}' not in category_details, skipping.")
            continue
        
        print(f"\n--- Training for category: {category} ---")
        weakness_info = {
            "category": category,
            "tasks": category_details[category].get("tasks", []),
            "current_score": category_details[category].get("mean", 0)
        }
        
        # Generate scenarios
        scenarios = generate_scenarios_for_weakness(weakness_info)
        print(f"Generated {len(scenarios)} scenarios for {category}")
        
        # Run training
        train_result = run_training(scenarios)
        training_results.append({
            "category": category,
            "scenarios_count": len(scenarios),
            "training_result": train_result
        })
        print(f"Training result: {train_result.get('status', 'unknown')}")
    
    # Step 3: Re-run evaluation to measure improvement
    print("\n=== Re-running evaluation after training ===")
    try:
        from run_full_golden_eval import run_evaluation
        eval_data_after = run_evaluation()
        if not eval_data_after:
            print("Re-evaluation failed.")
            sys.exit(1)
        
        category_means_after = eval_data_after["category_means"]
        overall_average_after = eval_data_after["overall_average"]
        
        # Compare before and after
        print("\n=== Improvement Report ===")
        category_means_before = training_data.get("all_category_means", {})
        overall_before = training_data.get("overall_average", 0)
        
        print(f"Overall average before: {overall_before:.3f}")
        print(f"Overall average after:  {overall_average_after:.3f}")
        print(f"Overall improvement:    {overall_average_after - overall_before:.3f}")
        
        print("\nCategory improvements:")
        for category, after_score in category_means_after.items():
            before_score = category_means_before.get(category, 0)
            improvement = after_score - before_score
            print(f"  {category}: {before_score:.3f} -> {after_score:.3f} ({improvement:+.3f})")
        
        # Save improvement report
        report = {
            "before": {
                "overall": overall_before,
                "categories": category_means_before
            },
            "after": {
                "overall": overall_average_after,
                "categories": category_means_after
            },
            "training_results": training_results,
            "improvements": {
                "overall": overall_average_after - overall_before,
                "categories": {cat: category_means_after.get(cat, 0) - category_means_before.get(cat, 0)
                               for cat in set(list(category_means_before.keys()) + list(category_means_after.keys()))}
            }
        }
        
        with open("training_report.json", "w") as f:
            json.dump(report, f, indent=2)
        print("\nTraining report saved to training_report.json")
        
    except Exception as e:
        print(f"Re-evaluation failed: {e}")
        print("You may need to run 'python run_full_golden_eval.py' again manually.")

if __name__ == "__main__":
    main()
